### ISSUE TITLE
Windows users: Please upgrade to Gridcoin 3.5.9.7

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/GRC#9]
We are waiting now for >157h on this upcoming superblock :-(

This means now: we had 3 long superblocks in a row which needed 293h so far (3rd is still needing time with birth)
* July 16: [67h](https://steemit.com/gridcoin/@erkan/superblock-967957-has-landed-includes-84-of-whitelisted-boinc-projects) (16%)
* July 19: [69h](https://aboutgridcoin.blogspot.de/2017/07/the-2nd-superblock-in-row-that-made-us.html) (downvoted on [steemit](https://steemit.com/gridcoin/@erkan/the-2nd-superblock-in-row-that-made-us-wait-so-long-includes-68-of-whitelisted-boinc-projects), please upvote) (68%)
* waiting so far >157h for this 3rd one

About 9h ago was [version 3.5.9.7](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-5-9-7-important-for-windows-users) released!
* If you run Windows: please upgrade!

![157](https://user-images.githubusercontent.com/642286/28604751-6b8aa29e-71cd-11e7-9005-ec1545d71ed3.png)

* [tweet](https://twitter.com/GridcoinIRC/status/890070388952182785)

----
* About steemit + github, read [this](https://github.com/Erkan-Yilmaz/GRC/blob/master/about.md) please.
* You like what I do? Read [this](https://github.com/Erkan-Yilmaz/GRC/blob/master/thank_you.md) please.

**Comment by SCCMAdmin** [comment]
Upgraded, cheers!

**Comment by Erkan-Yilmaz** [comment]
19h passed since the 3.5.9.7 was made available, but:
* still no SB, for >167h
  * not many upgraded to the .7 version? the SB problem lies somewhere else? ...
* these 167h are actually a **sad record** now, the last SB in that range was 1 month ago (on June 27): 
  * with 148h creation time (see picture above)
  * since June 20 the SB creation is in avg 55h (and median = 38h)

<br>

The devs are working hard:
* I. 5 new Gridcoin versions were released in the last 10 days 
* II. a **centralized** + **closedsource** server ([harvester](https://download.gridcoin.us/download/harvest/)) is used since a few weeks
  * tell that to someone in the/other blockchain/crypto communities and they will shake their heads

to try to solve parts of the superblock puzzle

<br>

I guess one option is to consider to make a **real mandatory** (and not a **pseudo** mandatory):
* like was done for the last 2 versions (announce in forum as mandatory, but not set the real mandatory "flag" (e.g. also with a fixed block height) for it)
* we did not have a real mandatory since 4 months (in April, version [3.5.8.8](https://github.com/gridcoin/Gridcoin-Research/releases/tag/3.5.8.8)) + there were so many SB fixes recently

With [such features](https://github.com/gridcoin/Gridcoin-Research/issues/114) (reported 11 months ago) we'd not need to run after the users and remind them to upgrade.

<br>

So, what will happen when a mandatory comes?
* likely we'll see a [fork](https://github.com/Erkan-Yilmaz/GRC/labels/fork), since some people will not upgrade fast enough
* hopefully... a new SB ?
* ...

Preparation time is needed though: 
* to reach out to service/exchanges, e.g. as in the [past](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/95)
* and that prep time will likely mean that the SB will make us wait even longer?

---

see also comments here: 
* [Gridcoin and thoughts (mandatory, ...)](https://steemit.com/gridcoin/@erkan/gridcoin-and-thoughts-mandatory)

**Comment by oshura3** [comment]
Good morning all, 

I will post my thoughts here as I have in the IRC chat but all in one place. I am not trying to come to the community with a problem but instead with a solution. Please take into consideration that my frame of reference is of one being a "newbie" to this whole Gridcoin thing so I may not know how everything works. At the same time, I'd assume that the thoughts I am putting down here would probably be had by other new people.

If a mandatory update would help solve this situation, make a "real" mandatory update happen. Some people might not know that they need to update their clients, either because they don't care to check or they don't know how to check.

One of the issues is that the wallet does not currently have a method of informing the user that an update is available other than by checking into the #gridcoin irc channel. If the wallet does not inform the user directly, they may never find out about the update. The user might just thing everything is a-ok since they haven't heard anything. 

User terminet3 suggested having a poll in the wallet that just asks "did you update your wallet? YES/NO" and that is a fantastic start. Maybe add into it, "Have you updated your wallet to MANDATORY version X.X.X.X yet? Yes/No" and make the poll free to take. That way we can keep track of where the problem is. 

Again, I want to reiterate this point because it is important, if the user does not know that they need to update, they most likely will not. If you make just ONE mandatory update for now to fix this issue, and explain *clearly* why it is absolutely essential, people are likely to understand. Don't just require a mandatory update and not explain why. Remember that many users don't have any working understanding of how the whole Gridcoin wallet thing works.

After the *one* mandatory update, just make it so the client does a pop-up message or something whenever there's another "mandatory" update informing us that we need to update our client at our earliest possible convenience.

It's understandable that some people may shake their heads at the idea of making an update mandatory but here moderation is key. As long as it's only ONE mandatory update every once in a while, it should not be a problem. As it stands, not having a consensus among our community is hurting the credibility of our community as a whole. 

Yes, this actual mandatory update might create a for but it seems that this would only place us at the same place we are now: without a superblock for almost a week.  I understand that I have not provided a way of how to fix the code (I wish I knew enough to help with that part out too) but my hope is for the community to grow together. 

The longer we wait to do what probably needs to happen anyways (the mandatory update so all the users are on the same page) the longer we will go "hoping" that the issue will resolve itself, when clearly this is not the first time it's happened. It seems from the links above that a solution has already been thought of. Let's just execute it.

Thank you for your consideration if you have read this far. I hope that this get's fixed soon.

Blessings,
Oshura3

**Comment by delordsquest** [comment]
Nice one Oshura3, I concur with your suggestion

**Comment by Erkan-Yilmaz** [comment]
summarizing parts of the discussion from IRC:
* we'd need to wait also, I think, at least 24h, until it is clear that the 3.5.9.7 really solves the problem. imagine announcing via poll the update and it doesn't really solve the SB prob
* more ways to inform: aggregate an RSS feed with news, [email](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/10)
* polls are not taken "seriously" ? and also small at bottom only
* tell exactly why it is important to upgrade
* something like boinc notices for gridcoin client, with desktop alert

**Comment by delordsquest** [comment]
I just want to appreciate the good work you are doing Mr. Erkan -Yilmaz, many thanks.

**Comment by Erkan-Yilmaz** [comment]
please use now 3.5.9.8, see #21
